{
 "title": "Malilog SIEM Dashboard (builded with JSON descriptor)",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Répartition protocoles de couche 4",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_l4_proto",
     "groupBy": [
      { "params": [ "l4_proto" ], "type": "tag" }
     ],
     "measurement": "Malilog-server-1",
     "query": "SELECT count(\"port_dst\") as occurences FROM \"Malilog-server-1\" WHERE $timeFilter GROUP BY \"l4_proto\"",
     "select": [
      [
       { "params": [ "port_dst" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Répartition des protocoles de couche 3",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_l3_proto",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"port_dst\")  FROM \"Malilog-server-1\" WHERE $timeFilter GROUP BY \"l3_proto\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Les 15 derniers évènements",
   "type": "table",
   "description": "Affichage des 15 dernières lignes de logs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT time,ip_src,port_src,ip_dst,port_dst,l3_proto, l4_proto,log_message FROM \"Malilog-server-1\" WHERE $timeFilter ORDER BY time DESC LIMIT 15 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Géolocalisation des visiteurs de l'application Malilog",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "src_geohash" ], "type": "tag" }
     ],
     "measurement": "Malilog-server-1",
     "query": "SELECT count(\"port_src\") AS \"metric\" FROM \"Malilog-server-1\" WHERE (\"src_geohash\" != 'UNKNOW') AND time > 0 GROUP BY \"src_geohash\"\n",
     "select": [
      [
       { "params": [ "port_src" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "src_geohash", "operator": "!=", "value": "UNKNOW" }
     ]
    }
   ]
  }
 ]
}